apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chatbot.name" . }}
  labels:
    app: stairling
    component: chatbot
    {{ include "chatbot.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chatbot.name" . }}
                port:
                  number: 8080