apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stairling.name" .  | default "stairling" }}
  labels:
    application: stairling
    component: backend
    {{- include "stairling.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      application: stairling
      component: backend
      {{- include "stairling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        application: stairling
        component: backend
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "stairling.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: api
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.vault.enabled }}
        vault.security.banzaicloud.io/vault-addr: {{ .Values.vault.url | quote }}
        vault.security.banzaicloud.io/vault-role: {{ .Values.vault.role | quote }}
        vault.security.banzaicloud.io/vault-skip-verify: {{ .Values.vault.skipVerify | quote }}
      {{- if and .Values.vault.envFrom.enabled .Values.vault.envFrom.path }}
        vault.security.banzaicloud.io/vault-env-from-path: {{ .Values.vault.envFrom.path }}
      {{- end }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ (include "stairling.serviceAccountName" .) | lower }}
      {{- end }}
      initContainers:
        - name: migration
          image: {{ include "stairling.image.migration" . }}
        {{- with .Values.initContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: api
          image: {{ include "stairling.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{ toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 4000
              name: api
              protocol: TCP
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      automountServiceAccountToken: {{ coalesce .Values.vault.enabled .Values.serviceAccount.token }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
