{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stairling.name" .  | default "stairling" }}
  labels:
    {{- include "stairling.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ .Values.service.name  | default "stairling" }}
                port:
                  number: {{ .Values.service.internalPort | default "3000" }}
            pathType: Prefix
  {{- end }}
