apiVersion: v1
kind: ServiceAccount
  {{- if .Values.image.pullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.image.pullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: {{ include "stairling.serviceAccountName" . }}
  labels:
  {{- include "stairling.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
