replicaCount: 1

name: &name chatbot-web

strategy: {}
#  type: Recreate
# Rollout sample
# canary:
#   maxSurge: 3
#   maxUnavailable: 0
#   canaryService: app-canary
#   stableService: app
#   steps:
#     - setWeight: 50
#     - pause: {}

image:
  repository: ghcr.io/stairlingtechnologies/chatbot-web
  tag: ''
  pullSecrets: []
  pullPolicy: Always
  #  - name: secret

ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
  class: nginx
  host: ''

serviceAccount:
  create: true
  token: true
  name: *name
  annotations: {}

env: []

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
podAnnotations: {}
podLabels: {}
resources: {}
nodeSelector: {}
affinity: {}
tolerations: []

vault:
  enabled: true
  role: ''
  skipVerify: "true"
  url: ''
  envFrom:
    enabled: false
    path: ''

initContainers: []

extraVolumes: []
extraVolumeMounts: []
extraContainers: []
preInitContainers: []
extraResources: ""
